### PR TITLE
Chat loading bug

### PR DESCRIPTION
**Pull request by Bakushin10**
The issue of loading the data in random order was not the issue of the mongoDB. It was loading the data from the db without sorting it. so I added the sorting method by date to fix it.

### CODE REVIEW

**Review by pryanalewis — APPROVED** [review]
Looks good to me!

**Comment by tjsparks5** [comment]
The chat history loads in the correct order, but whenever I click send on a new message it is still being added above everything instead of at the bottom beneath the latest messages.

**Comment by Bakushin10** [comment]
@tjsparks5 This pull request only addresses the issue of loading the data from db. The problem you pointed out is a front end issue and @pryanalewis  and I are working on it in different branch, and it will be fixed in that branch.

**Review by tjsparks5 — APPROVED** [review]
Ah ok. Then yep everything looks good for this pull request. Sorry about that.

**Pull request merged**
