### PR TITLE
Chat rooms

### PR DESCRIPTION
**Pull request by Bakushin10**
### what was implemented 

1. multiple chat room. You only see the messages in the particular chat room. For example, you don't see messages that are sent to chat room A if you are in chat room B.
2. empty message issue fixed. You can't send empty messages.

### How to test 

Open up localhost in 2 different tabs(windows). 
1. test to see if you can retrieve the messages if you are in the same chat rooms. 
2. test to see if you won't see the messages if you are in the different chat rooms.

### CODE REVIEW

**Comment by tjsparks5** [comment]
Everything looks great!

**Review by tjsparks5 — APPROVED** [review]

**Review by TDinaso559 — APPROVED** [review]
Everything looks to be working for me! Good work.

**Review by pryanalewis — APPROVED** [review]
Worked for me! Looks great!

**Review by yotoo2920 — APPROVED** [review]
Works great, messages only appear in each chat.

**Pull request merged**
