### PR TITLE
Large loading times and duplicate classes fix

### PR DESCRIPTION
**Pull request by tjsparks5**
- Fixed the issue with large loading times when switching views after adding a class (issue #52).
- Fixed the issue with duplicate classes (issue #53).

**Note**: In issue #53 I detailed how the duplicate class used to happen. Now a duplicate should not occur when following the steps.

### CODE REVIEW

**Review by yotoo2920 — APPROVED** [review]
It is working as Flash rn, damn fast.

**Review by TDinaso559 — APPROVED** [review]
Working real fast on mine. Also not getting duplicates too

**Review by pryanalewis — APPROVED** [review]
Everything was working great and fast for me!

**Review by Bakushin10 — APPROVED** [review]
checked it

**Review by abcooper — COMMENTED** [review]
Looks good to me

**Pull request merged**
