### PR TITLE
fixed masterTemp

### PR DESCRIPTION
**Pull request by yotoo2920**
Please review everything
1- the only thing that is not working for me is Password recovery. Maybe my development file is not good
2- grunt is working for me without giving any error that crash the app

### CODE REVIEW

**Comment by Bakushin10** [comment]
Please fix these two errors before making a pull request. 
if you still have bugs in your pull request, you should not be making one.

**Comment by yotoo2920** [comment]
You right, I will fix the recovery password and I will let you guys know. Besides that if your app is crashing as Shin' is. masterTemp will fix this problem

**Comment by tjsparks5** [comment]
Everything is working fine for me, including password recovery. Tested it on my local.

**Review by tjsparks5 — APPROVED** [review]

**Review by pryanalewis — COMMENTED** [review]
Hey everything is working except the password recovery on mine as well. When I clicked forgot password it says "unable to send email"

**Comment by yotoo2920** [comment]
Pryana, my guessing is that it will be a small difference in development.js file since it is the file related to password. Since Tyler, got it working! we should be good...

**Pull request closed without merging**
