### PR TITLE
updated gitignore file to ignore macOS related files

### PR DESCRIPTION
**Pull request by yotoo2920**
No other file than .gitignore was changed, but please verify that your app works as expected.

### CODE REVIEW

**Review by Bakushin10 — CHANGES_REQUESTED** [review]
make sure to merge from master once Pryana's branch is merged

**Comment by Bakushin10** [comment]
Can you describe what the changes for?

**Review by TDinaso559 — APPROVED** [review]
My app still works. If that's all you wanted us to check, then it's good

**Comment by yotoo2920** [comment]
Will do the change together with the deployment

**Pull request closed without merging**
