### PR TITLE
Test : Update UI for the homepage and Chat

### PR DESCRIPTION
**Pull request by yotoo2920**
Just checked test all the css looks ok, except by the merged chat.html

### CODE REVIEW

**Review by tjsparks5 — APPROVED** [review]
Everything looks good. I don't see any issues.

**Comment by tjsparks5** [comment]
The problem you are probably seeing with the chat is because the model for the chat data was updated. @Bakushin10 has the new retrieval function that works with the new model in his branch.

**Comment by yotoo2920** [comment]
Yes @tjsparks5 I agreed, I just did not want to mess with it since the backend is more important now that @pryanalewis will put some girls touches in the UI.

**Review by Bakushin10 — APPROVED** [review]
works fine. chat history is not loading correctly since the model was updated like Tyler mentioned.

**Pull request merged**
