### PR TITLE
Home page2

### PR DESCRIPTION
**Pull request by Bakushin10**
what was implemented
- removed the homepage. the users will be navigated to chat when they open the app 

**there is a lag when you open the app and you are already signed in. it will take you to chat but it shows the empty homepage for like 0.5 seconds.**

### CODE REVIEW

**Review by abcooper — COMMENTED** [review]
Looks good

**Review by tjsparks5 — CHANGES_REQUESTED** [review]
Whenever you navigate to localhost:27017 with no additional routes such as "/chat", it goes to a weird page.

**Comment by pryanalewis** [comment]
The same thing that happened to Tyler happened to me.

**Comment by pryanalewis** [comment]
Looks good to me, works like you said!

**Review by TDinaso559 — APPROVED** [review]
Working good for me. Nice work.

**Review by tjsparks5 — APPROVED** [review]

**Comment by tjsparks5** [comment]
Tested the changes you made. Works great.

**Pull request merged**
