### PR TITLE
Additional UI updates

### PR DESCRIPTION
**Pull request by pryanalewis**
**Things to look at**

- I updated the logo on the hompage ,signup, and signin pages
- Fixed the chat scrolling so that it behaves like a normal chat
- Added a message that displays on the chat page in the list of classes div, that displays only if a user has no classes added
- Updated some content on the homepage, and commented out the links in the footer since they are not used

### CODE REVIEW

**Review by yotoo2920 — APPROVED** [review]
Everything looks great, loved it :)

**Review by TDinaso559 — APPROVED** [review]
Looks good! Scrolling worked just like you said, and I'm glad we changed the color of the logo on the home page! Looks a lot better

**Review by tjsparks5 — APPROVED** [review]
Everything looks great!

**Review by Bakushin10 — COMMENTED** [review]
added the submit button disable when no classes are selected. 
scrolling did not really work for me when new chats are coming in

**Pull request merged**
