### PR TITLE
Password recovery

### PR DESCRIPTION
**Pull request by Bakushin10**
modified 
- changed the setting for password recovery 

test 
- test to see you can get an email and be able to change your password.

### CODE REVIEW

**Comment by Bakushin10** [comment]
one thing though, the file needs to be protected as it has email and password.

**Review by yotoo2920 — CHANGES_REQUESTED** [review]
1- add a development.example.js

**Comment by Bakushin10** [comment]
what should be inside of  development.example.js?
I also changed .gitignore file

**Comment by yotoo2920** [comment]
Exactly the code you have developed for the password to work just change the real info, 
eg: ' <user password> ' where real password is in line 66 in the file you were trying to merge into git

**Review by pryanalewis — APPROVED** [review]
I reset my password twice and it worked for me. I had to create a new account though because I put some fake email on the first account..

**Comment by Bakushin10** [comment]
I will upload the development.example.js and wait for Dario's approval.

@pryanalewis How did you test it ? Did you pull this branch on your local ? I think in this stage( branch -> test) you are supposed to review only code. And once the branch is merged to test, then you pull it to your local and test. But I appreciate your reviewing!!

**Comment by yotoo2920** [comment]
@Bakushin10 after you get the development.example.js file, you can feel free to do that pull request to master! Great job man. @pryanalewis thanks for reviewing Shin's work

**Review by yotoo2920 — COMMENTED** [review]
Great work, it is intuitive to understand what info should be really in

**Pull request merged**
