### PR TITLE
Test: chat server side 

### PR DESCRIPTION
**Pull request by Bakushin10**
things to test 
- to be able to save the chat data to db and reload the data when the page is loaded and another person posts on the chat room asynchronously.

- bug : grunt might not work for this, so use node server to run the app

### CODE REVIEW

**Comment by tjsparks5** [comment]
Dario and I tested and here is what we found: The data is saved to the database correctly and each time the page is refreshed the chat history is loaded correctly, but it does not automatically load whenever another user sends a message in the chat. When Dario and I were both signed in his messages would not automatically load for me, I would have to manually refresh for his messages to show up, same goes for me sending to him.

**Comment by Bakushin10** [comment]
You can think of this problem as you guys are in different chat room, but sharing the same space(db) to store the info. if you open two tabs on your PC and try talking to each other then it should work, this is because they are on the same URL. Its hard to test now because you two are on different network. thats what I think the problem is.  

But you are right about it and we need to find a way to test it. All we can do to test is to open the multiple local host on your PC and chat.

**Review by tjsparks5 — APPROVED** [review]
Tested on my local. The chat updates to the database and retrieves the chat history from the database correctly. When two users are signed in on the server the chat updates automatically. Everything looks good.

**Comment by tjsparks5** [comment]
Yes sorry about deleting my original comment. I realized the issue was that Dario and I were on two separate servers. When signed in on two separate accounts on the same server the chat works as intended. Dario mentioned this may involve further testing once it rolls out for production, but for now I think it is fine.

**Review by yotoo2920 — APPROVED** [review]
I agreed with your guys comments on here and on groupMe. It was great we came with this shortcut testing the chat.

**Pull request merged**
