### PR TITLE
Branch ready for deploy

### PR DESCRIPTION
**Pull request by yotoo2920**
- Check that app works as it should

### CODE REVIEW

**Comment by yotoo2920** [comment]
As @tjsparks5 pointed out I created the PR from the wrong branch, so I reopen the same PR from test branch

**Review by tjsparks5 — APPROVED** [review]
Tested it locally. Everything looks great.

**Review by TDinaso559 — APPROVED** [review]
Good catch by Tyler! Works good for me as well.

**Review by pryanalewis — APPROVED** [review]
Everything looked great to me!

**Pull request merged**
