### PR TITLE
Added test

### PR DESCRIPTION
**Pull request by abcooper**
Make sure you install mongod and have it running when attempting to test. https://treehouse.github.io/installation-guides/mac/mongo-mac.html
The app will also run port 27017 now.

### CODE REVIEW

**Review by tjsparks5 — APPROVED** [review]
The tests ran successfully for me.

**Review by TDinaso559 — APPROVED** [review]
Was able to see all the tests.

**Review by Bakushin10 — APPROVED** [review]
checked the test. testing worked fine

**Review by yotoo2920 — APPROVED** [review]
I was able to run the testes

**Pull request merged**
