### PR TITLE
Test: retrieve chat data for each class  

### PR DESCRIPTION
**Pull request by Bakushin10**
things to test 
- to be able to switch between chats, and chat loads correct data.
- if you say something on a particular chat, you won't see the conversation on other chats.

courses to add to see the conversation 

1. - ABE 3000C | Applications in Biological Engineering
2. - ABE 2062 | Biology for Engineers

##   Known bug 

when the course with no chat history is selected, it gives an error. I'm working on it to fix it 

- [x] update: the bug is now fixed

### CODE REVIEW

**Review by tjsparks5 — APPROVED** [review]
Tested on my local. When switching between the chats the history for the correct chat loaded. When sending a message in a chat the message is saved in the correct chat's history.

**Review by pryanalewis — APPROVED** [review]
Everything works well for me, I was able to add the classes and see the history!

**Comment by tjsparks5** [comment]
I tested the fix Shin made as well. Everything looks good.

**Comment by Bakushin10** [comment]
duplicate error was fixed.

**Pull request merged**
