### PR TITLE
UI for the entire site

### PR DESCRIPTION
**Pull request by pryanalewis**
When checking this request I suggest going through all the pages both for admin and normal users to find any thing I should change/fix. So far I think it is looking pretty good. 

For now the only things I couldn't figure out are getting the chats to scroll to the bottom automatically and the text box to get larger as more text is inputted.

### CODE REVIEW

**Comment by yotoo2920** [comment]
Wow @pryanalewis This new UI looks so much better. Great Work :)

**Review by yotoo2920 — APPROVED** [review]
I loved it, the colors go pretty good together. The home page w/ the new pics looks pretty nice

**Review by Bakushin10 — CHANGES_REQUESTED** [review]
Looks great! but this branch needs to be merged from master once chat room branch is merged. I will push these changes, and then I will approve.

**Review by tjsparks5 — COMMENTED** [review]
Everything looks great! I agree with Shin. Make sure to merge with master once Shin's pull request is accepted, then I think it'll be good to go.

**Comment by Bakushin10** [comment]
I merged master into UI

**Review by Bakushin10 — APPROVED** [review]

**Pull request merged**
