### PR TITLE
Adding news module to master

### PR DESCRIPTION
**Pull request by yotoo2920**

### CODE REVIEW

**Comment by Bakushin10** [comment]
there is no description for this pull request, so I do not know where you want me to review.
Also you need to mention where you want me to test as well.

**Review by Bakushin10 — CHANGES_REQUESTED** [review]
Please resolve the merge conflict

**Comment by yotoo2920** [comment]
Working on it

**Comment by Bakushin10** [comment]
Please provide the description of what to test for this branch

**Comment by yotoo2920** [comment]
I fixed the damn merge issue!

**Comment by yotoo2920** [comment]
You are right, next time I do the pull request to test I will be more careful with indications

**Pull request merged**
